/**
 * Routing history log — append-only record of promotions/demotions for
 * `alpha-loop evolve routing`. Stored as markdown at
 * `.alpha-loop/learnings/routing-history.md` so humans can skim it and the
 * proposer agent can read it directly when proposing the next change.
 */
import { existsSync, mkdirSync, readFileSync, appendFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { latestMatrixRun } from './eval-matrix.js';

/** Action recorded in the routing history file. */
export type RoutingHistoryAction = 'promote' | 'demote' | 'manual_demote';

/** A single entry appended to routing-history.md. */
export type RoutingHistoryEntry = {
  timestamp: string;
  action: RoutingHistoryAction;
  stage: string;
  from: { model: string; endpoint?: string };
  to: { model: string; endpoint?: string };
  reason: string;
  metrics?: Record<string, number | string | null>;
  prUrl?: string;
};

/** Path to the history file, relative to the project root. */
export const ROUTING_HISTORY_PATH = '.alpha-loop/learnings/routing-history.md';

const HISTORY_HEADER = '# Routing History\n\nAppend-only record of promotions and demotions generated by `alpha-loop evolve routing`.\n';

function historyFile(projectDir: string): string {
  return join(projectDir, ROUTING_HISTORY_PATH);
}

/**
 * Append a routing history entry. Creates the file (with a header) on first
 * write. Each entry is a markdown section so the file stays human-readable.
 */
export function appendRoutingHistory(entry: RoutingHistoryEntry, projectDir: string = process.cwd()): void {
  const filePath = historyFile(projectDir);
  mkdirSync(join(projectDir, '.alpha-loop', 'learnings'), { recursive: true });

  if (!existsSync(filePath)) {
    writeFileSync(filePath, HISTORY_HEADER + '\n');
  }

  const lines: string[] = [];
  lines.push(`## ${entry.timestamp} — ${entry.action} ${entry.stage}`);
  lines.push('');
  lines.push(`- **Action:** ${entry.action}`);
  lines.push(`- **Stage:** ${entry.stage}`);
  lines.push(`- **From:** ${formatTarget(entry.from)}`);
  lines.push(`- **To:** ${formatTarget(entry.to)}`);
  lines.push(`- **Reason:** ${entry.reason}`);
  if (entry.prUrl) lines.push(`- **PR:** ${entry.prUrl}`);
  if (entry.metrics && Object.keys(entry.metrics).length > 0) {
    lines.push('- **Metrics:**');
    for (const [k, v] of Object.entries(entry.metrics)) {
      lines.push(`  - ${k}: ${v ?? 'n/a'}`);
    }
  }
  lines.push('');

  appendFileSync(filePath, lines.join('\n'));
}

/**
 * Read all routing history entries. Returns an empty array when the file does
 * not exist. Entries come back in file order (oldest → newest).
 */
export function readRoutingHistory(projectDir: string = process.cwd()): RoutingHistoryEntry[] {
  const filePath = historyFile(projectDir);
  if (!existsSync(filePath)) return [];
  const content = readFileSync(filePath, 'utf-8');
  return parseHistory(content);
}

function parseHistory(content: string): RoutingHistoryEntry[] {
  const entries: RoutingHistoryEntry[] = [];
  const sections = content.split(/\n## /).slice(1);
  for (const raw of sections) {
    const section = '## ' + raw;
    const headingMatch = section.match(/^## (\S+) — (\S+) (\S+)/);
    if (!headingMatch) continue;
    const [, timestamp, action, stage] = headingMatch;

    const fromMatch = section.match(/- \*\*From:\*\* (.+)/);
    const toMatch = section.match(/- \*\*To:\*\* (.+)/);
    const reasonMatch = section.match(/- \*\*Reason:\*\* (.+)/);
    const prMatch = section.match(/- \*\*PR:\*\* (.+)/);

    entries.push({
      timestamp,
      action: action as RoutingHistoryAction,
      stage,
      from: parseTarget(fromMatch?.[1]),
      to: parseTarget(toMatch?.[1]),
      reason: (reasonMatch?.[1] ?? '').trim(),
      prUrl: prMatch?.[1]?.trim(),
    });
  }
  return entries;
}

function formatTarget(t: { model: string; endpoint?: string }): string {
  return t.endpoint ? `${t.model} @ ${t.endpoint}` : t.model;
}

function parseTarget(raw: string | undefined): { model: string; endpoint?: string } {
  if (!raw) return { model: '' };
  const match = raw.trim().match(/^(.+?)(?:\s+@\s+(.+))?$/);
  if (!match) return { model: raw.trim() };
  return { model: match[1].trim(), endpoint: match[2]?.trim() };
}

/**
 * Return the mtime (ms) of the most recent matrix report, or null when no
 * report has been written.
 */
export function latestMatrixRunTime(projectDir: string = process.cwd()): number | null {
  const latest = latestMatrixRun(projectDir);
  return latest ? latest.timestampMs : null;
}

/** 7-day freshness window in milliseconds. */
export const MATRIX_FRESHNESS_WINDOW_MS = 7 * 24 * 60 * 60 * 1000;

/**
 * Return true when the most recent matrix report is within the freshness
 * window. `nowMs` is injectable for tests.
 */
export function isMatrixFresh(
  projectDir: string = process.cwd(),
  nowMs: number = Date.now(),
  windowMs: number = MATRIX_FRESHNESS_WINDOW_MS,
): boolean {
  const latest = latestMatrixRunTime(projectDir);
  if (latest == null) return false;
  return nowMs - latest <= windowMs;
}
